-- tests/spec_notes.lua
-- Notes with several named topics plus an optional floating window. The window
-- collapses to a compact "Do ^" pill, can be moved, closed and styled, and is
-- read-only during combat. The options tab mirrors the same topics.
local function click(widget, ...)
	widget:GetScript("OnClick")(widget, ...)
end

local function contains(text, fragment)
	return type(text) == "string" and text:find(fragment, 1, true) ~= nil
end

T.register("notes: tab switches cleanly and edits persist and mirror between editors", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	assert_false(f.notesPage:IsShown())
	click(f.controls.notesTab)
	assert_eq(f.selectedTab, "notes")
	assert_true(f.notesPage:IsShown())
	assert_false(f.settingsPage:IsShown())
	assert_false(f.spellsPage:IsShown())
	assert_true(contains(f.controls.notesTab:GetText(), "Notes"))
	f.notesEditor:SetText("flask timer\npull at 3")
	assert_eq(e.ns.db.notes.sites[1].text, "flask timer\npull at 3")
	local win = e.ns.notes.Open()
	assert_true(win:IsShown())
	assert_eq(win.edit:GetText(), "flask timer\npull at 3")
	win.edit:SetText("updated")
	assert_eq(e.ns.db.notes.sites[1].text, "updated")
	assert_eq(f.notesEditor:GetText(), "updated")
	assert_nil(win:GetScript("OnUpdate"), "notes window has no idle updater")
	-- Selecting another tab hides notes but keeps the persisted text.
	click(f.controls.spellsTab)
	assert_false(f.notesPage:IsShown())
	assert_eq(e.ns.db.notes.sites[1].text, "updated")
end)

T.register("notes: topics keep separate text and selection survives switching", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	click(f.controls.notesTab)
	assert_eq(#e.ns.notes.Sites(), 1, "a fresh install starts with one topic")
	assert_eq(e.ns.notes.ActiveSite().title, "General")
	f.notesEditor:SetText("first")
	click(f.controls.notesNew)
	assert_eq(#e.ns.notes.Sites(), 2)
	assert_eq(e.ns.notes.ActiveSite().title, "Note 2")
	f.notesEditor:SetText("second")
	assert_eq(e.ns.notes.SiteText(e.ns.notes.ActiveId()), "second")
	assert_eq(f.controls.notesTitle:GetText(), "Note 2")
	-- Switch back to the first topic; its text is intact and shown in the editor.
	click(f.controls.notesPrev)
	assert_eq(e.ns.notes.SiteText(e.ns.notes.ActiveId()), "first")
	assert_eq(f.notesEditor:GetText(), "first")
	-- Rename the active topic.
	f.controls.notesTitle:SetText("Raiding")
	f.controls.notesTitle:GetScript("OnEnterPressed")(f.controls.notesTitle)
	assert_eq(e.ns.notes.ActiveSite().title, "Raiding")
	assert_eq(f.controls.notesTitle:GetText(), "Raiding")
	-- Delete it; one topic must always remain.
	assert_eq(#e.ns.notes.Sites(), 2)
	click(f.controls.notesDelete)
	assert_eq(#e.ns.notes.Sites(), 1)
	click(f.controls.notesDelete)
	assert_eq(#e.ns.notes.Sites(), 1, "the last topic is never removed")
	assert_eq(f.notesEditor:GetText(), "second")
end)

T.register("notes: floating window adds, renames, cycles and deletes topics", function()
	local e = Mocks.NewEnv()
	local f = e.ns.notes.Open()
	f.edit:SetText("alpha")
	assert_eq(e.ns.notes.SiteText(e.ns.notes.ActiveId()), "alpha")
	click(f.siteAdd)
	assert_eq(#e.ns.notes.Sites(), 2)
	assert_eq(f.edit:GetText(), "", "a new topic starts empty")
	f.edit:SetText("beta")
	click(f.sitePrev)
	assert_eq(f.edit:GetText(), "alpha")
	assert_eq(f.siteTitle:GetText(), e.ns.notes.ActiveSite().title)
	f.siteTitle:SetText("Gear")
	f.siteTitle:GetScript("OnEnterPressed")(f.siteTitle)
	assert_eq(e.ns.notes.ActiveSite().title, "Gear")
	click(f.siteNext)
	assert_eq(f.edit:GetText(), "beta")
	assert_eq(f.siteTitle:GetText(), "Note 2")
	click(f.siteDel)
	assert_eq(#e.ns.notes.Sites(), 1)
end)

T.register("notes: legacy single text migrates into a first topic without loss", function()
	local e = Mocks.NewEnv()
	-- Simulate the pre-topics SavedVariables schema.
	e.ns.db.notes.sites = nil
	e.ns.db.notes.text = "old note body"
	local sites = e.ns.notes.Sites()
	assert_eq(#sites, 1)
	assert_eq(sites[1].title, "General")
	assert_eq(sites[1].text, "old note body")
	assert_nil(e.ns.db.notes.text, "the legacy field is migrated away, not kept in parallel")
	-- A second call never duplicates or clears the migrated topic.
	assert_eq(#e.ns.notes.Sites(), 1)
	assert_eq(e.ns.notes.SiteText(e.ns.notes.ActiveId()), "old note body")
end)

T.register("notes: editing locks in combat and unlocks afterwards", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	click(f.controls.notesTab)
	local win = e.ns.notes.Open()
	local ev = e.ns.notes.eventFrame
	assert_not_nil(ev, "notes owns a small event frame")
	win.edit:SetFocus()
	e.ns.notes.RefreshEditable()
	assert_true(win.edit:IsEnabled())
	Mocks.inCombat = true
	e.ns.notes.eventFrame:GetScript("OnEvent")(ev, "PLAYER_REGEN_DISABLED")
	assert_false(e.ns.notes.IsEditable())
	assert_false(win.edit:IsEnabled(), "floating editor is read-only in combat")
	assert_false(f.notesEditor:IsEnabled(), "tab editor is read-only in combat")
	assert_false(win.edit:HasFocus(), "locking clears focus so keybinds are not swallowed")
	assert_false(win.siteTitle:IsEnabled(), "topic title is read-only in combat")
	assert_false(win.siteAdd:IsEnabled(), "adding a topic is blocked in combat")
	assert_false(win.siteDel:IsEnabled(), "deleting a topic is blocked in combat")
	assert_false(f.controls.notesTitle:IsEnabled(), "tab topic title is read-only in combat")
	assert_false(f.controls.notesNew:IsEnabled(), "tab add is blocked in combat")
	assert_true(win.sitePrev:IsEnabled(), "cycling topics is safe in combat")
	assert_true(contains(win.hint:GetText(), "read-only"))
	Mocks.inCombat = false
	e.ns.notes.eventFrame:GetScript("OnEvent")(ev, "PLAYER_REGEN_ENABLED")
	assert_true(e.ns.notes.IsEditable())
	assert_true(win.edit:IsEnabled())
	assert_true(win.siteAdd:IsEnabled())
	assert_true(f.controls.notesNew:IsEnabled())
	assert_eq(win.hint:GetText(), "")
end)

T.register("notes: collapsed pill is compact, shows Do and arrow, and reopens", function()
	local e = Mocks.NewEnv()
	local f = e.ns.notes.Open()
	assert_true(f:IsShown())
	assert_true(e.ns.db.notes.shown)
	assert_eq(f.title:GetText(), "Do")
	assert_eq(f.collapse:GetText(), "v")
	-- Collapsed: just "Do" and the arrow, much smaller than the editor window.
	click(f.collapse)
	assert_true(e.ns.db.notes.collapsed)
	assert_false(f.edit:IsShown())
	assert_eq(f:GetHeight(), e.ns.notes.COLLAPSED_HEIGHT)
	assert_eq(f:GetWidth(), e.ns.notes.COLLAPSED_WIDTH)
	assert_eq(f.collapse:GetText(), "^")
	assert_false(f.close:IsShown(), "the collapsed pill keeps only the expand arrow")
	assert_false(f.siteTitle:IsShown())
	-- The arrow opens it again.
	click(f.collapse)
	assert_false(e.ns.db.notes.collapsed)
	assert_true(f.edit:IsShown())
	assert_true(f.close:IsShown())
	assert_eq(f.collapse:GetText(), "v")
	f:GetScript("OnDragStart")(f)
	assert_true(f._moving)
	f:GetScript("OnDragStop")(f)
	assert_false(f._moving)
	assert_eq(e.ns.db.notes.x, 0)
	assert_eq(e.ns.db.notes.y, 0)
	click(f.close)
	assert_false(f:IsShown())
	assert_false(e.ns.db.notes.shown)
	e.ns.db.notes.shown = true
	e.ns.notes.HandleEvent("PLAYER_LOGIN")
	assert_true(f:IsShown(), "a shown note is restored after a reload")
	e.ns.HandleCommand("notes hide")
	assert_false(f:IsShown())
	e.ns.HandleCommand("notes expand")
	e.ns.HandleCommand("notes")
	assert_true(f:IsShown())
	assert_eq(e.ns.notes.window, f, "the window is reused lazily")
end)

T.register("notes: style applies live, is validated atomically and resets to defaults", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	click(f.controls.notesTab)
	local c = f.controls
	c.notesWidth:SetText("400"); c.notesHeight:SetText("300"); c.notesFont:SetText("18")
	c.notesTextR:SetText("1"); c.notesTextG:SetText("0.5"); c.notesTextB:SetText("0")
	c.notesBgR:SetText("0"); c.notesBgG:SetText("0.1"); c.notesBgB:SetText("0.2"); c.notesBgA:SetText("0.5")
	click(c.notesApply)
	assert_eq(e.ns.db.notes.width, 400)
	assert_eq(e.ns.db.notes.height, 300)
	assert_eq(e.ns.db.notes.fontSize, 18)
	assert_eq(e.ns.db.notes.textColor[2], 0.5)
	assert_eq(e.ns.db.notes.background[4], 0.5)
	local win = e.ns.notes.EnsureWindow()
	assert_eq(win:GetWidth(), 400)
	assert_eq(win:GetHeight(), 300)
	local _, size = win.edit:GetFont()
	assert_eq(size, 18)
	-- An out-of-range value leaves every stored field untouched.
	c.notesWidth:SetText("10")
	click(c.notesApply)
	assert_eq(e.ns.db.notes.width, 400)
	c.notesWidth:SetText("400")
	c.notesFont:SetText("nan")
	click(c.notesApply)
	assert_eq(e.ns.db.notes.fontSize, 18)
	click(c.notesReset)
	assert_eq(e.ns.db.notes.width, e.ns.DEFAULTS.notes.width)
	assert_eq(e.ns.db.notes.fontSize, e.ns.DEFAULTS.notes.fontSize)
end)

T.register("notes: text is capped and refuses secret or non-string input", function()
	local e = Mocks.NewEnv()
	assert_false(e.ns.notes.SetText(Mocks.MakeSecret()))
	assert_false(e.ns.notes.SetText(42))
	e.ns.notes.SetText(string.rep("x", 30000))
	assert_eq(#e.ns.notes.SiteText(e.ns.notes.ActiveId()), 20000)
	local f = e.ns.notes.Open()
	assert_eq(#f.edit:GetText(), 20000)
	assert_eq(e.ns.notes.Text(), e.ns.notes.SiteText(e.ns.notes.ActiveId()))
end)

T.register("notes: floating window labels stay visible and no idle updater exists", function()
	local e = Mocks.NewEnv()
	local f = e.ns.notes.Open()
	assert_nil(f:GetScript("OnUpdate"))
	assert_not_nil(f._backdrop, "notes window has a styled background")
	local title = Mocks.FindFontString(f, "Do")
	assert_not_nil(title, "the compact notes title must exist")
	assert_true(Mocks.IsRegionVisible(title), "notes title must not be occluded by its editor")
end)

T.register("notes: saved style reaches the tab editor when options opens afterwards", function()
	local e = Mocks.NewEnv()
	assert_true(e.ns.notes.SetStyle({ width = 420, height = 260, fontSize = 20,
		textColor = { 1, 1, 1 }, background = { 0, 0, 0, 1 } }))
	local f = e.ns.OpenOptions()
	click(f.controls.notesTab)
	local _, tabSize = f.notesEditor:GetFont()
	assert_eq(tabSize, 20, "tab editor must adopt the persisted font size")
	local win = e.ns.notes.EnsureWindow()
	local _, winSize = win.edit:GetFont()
	assert_eq(winSize, 20)
end)

T.register("notes: hiding the floating window clears editor focus", function()
	local e = Mocks.NewEnv()
	local f = e.ns.notes.Open()
	f.edit:SetFocus()
	assert_true(f.edit:HasFocus())
	click(f.close)
	assert_false(f:IsShown())
	assert_false(f.edit:HasFocus(), "a closed editor must not keep keyboard focus")
end)

T.register("notes: defaults recover from a wrongly typed saved notes table", function()
	local e = Mocks.NewEnv()
	local merged = e.ns.applyDefaults({ notes = "corrupt" }, e.ns.DEFAULTS)
	assert_true(type(merged.notes) == "table", "a non-table saved value is replaced by defaults")
	assert_eq(merged.notes.width, e.ns.DEFAULTS.notes.width)
	assert_true(type(merged.notes.textColor) == "table")
	assert_eq(merged.notes.textColor[1], e.ns.DEFAULTS.notes.textColor[1])
	assert_true(type(merged.notes.sites) == "table")
end)

T.register("notes: corrupt topic entries are repaired, not duplicated or lost", function()
	local e = Mocks.NewEnv()
	-- A saved list with a bad entry is rebuilt, keeping the valid one.
	e.ns.db.notes.sites = { { id = "site-7", title = "Keep", text = "body" }, { id = 5, title = "bad" } }
	local sites = e.ns.notes.Sites()
	assert_eq(#sites, 1)
	assert_eq(sites[1].text, "body")
	-- AddSite never collides with an existing id.
	local site = e.ns.notes.AddSite("Second")
	assert_not_nil(site)
	assert_true(site.id ~= "site-7")
	assert_eq(#e.ns.notes.Sites(), 2)
end)

T.register("notes: slash commands manage topics and select by name or index", function()
	local e = Mocks.NewEnv()
	e.ns.HandleCommand("notes new Raiding")
	assert_eq(#e.ns.notes.Sites(), 2)
	assert_eq(e.ns.notes.ActiveSite().title, "Raiding")
	e.ns.notes.SetText("flask at pull")
	e.ns.HandleCommand("notes new Gold")
	e.ns.HandleCommand("notes prev")
	assert_eq(e.ns.notes.ActiveSite().title, "Raiding")
	e.ns.HandleCommand("notes site 1")
	assert_eq(e.ns.notes.ActiveSite().title, "General")
	e.ns.HandleCommand("notes site gold")
	assert_eq(e.ns.notes.ActiveSite().title, "Gold")
	e.ns.HandleCommand("notes list")
	assert_true(#Mocks.chat > 0, "list prints the topics")
	e.ns.HandleCommand("notes delete")
	assert_eq(#e.ns.notes.Sites(), 2)
	e.ns.HandleCommand("notes delete")
	e.ns.HandleCommand("notes delete")
	assert_eq(#e.ns.notes.Sites(), 1, "the last topic survives repeated deletes")
end)

T.register("notes: binding entry point toggles the floating window", function()
	local e = Mocks.NewEnv()
	assert_true(type(EllesmereUI_HoTPrediction_ToggleNotes) == "function")
	EllesmereUI_HoTPrediction_ToggleNotes()
	assert_true(e.ns.notes.window:IsShown())
	EllesmereUI_HoTPrediction_ToggleNotes()
	assert_false(e.ns.notes.window:IsShown())
end)
