local function click(widget, ...)
	widget:GetScript("OnClick")(widget, ...)
end
local function toggle(widget, value)
	widget:SetChecked(value)
	click(widget)
end

T.register("options: window is lazy reused escape registered and refreshes saved settings", function()
	local e = Mocks.NewEnv()
	assert_nil(e.ns.optionsWindow)
	e.ns.HandleCommand("options")
	local f = e.ns.optionsWindow
	assert_true(f:IsShown())
	assert_eq(f.controls.alpha:GetText(), "0.6")
	assert_true(f.controls.enabled:GetChecked())
	assert_false(f.controls.approximate:GetChecked())
	click(f.controls.close)
	assert_false(f:IsShown())
	e.ns.HandleCommand("alpha 0.25")
	e.ns.HandleCommand("menu")
	assert_eq(e.ns.optionsWindow, f)
	assert_eq(f.controls.alpha:GetText(), "0.25")
	local found = 0
	for _, name in ipairs(UISpecialFrames) do if name == f:GetName() then found = found + 1 end end
	assert_eq(found, 1)
	assert_nil(f:GetScript("OnUpdate"))
end)

T.register("options: checkboxes use existing runtime and prediction commands", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	toggle(f.controls.approximate, true)
	assert_true(e.ns.db.approximatePrediction)
	toggle(f.controls.exclude, true)
	assert_true(e.ns.db.assumeApiExcludesHoTs)
	toggle(f.controls.enabled, false)
	assert_false(e.ns.db.enabled)
	assert_nil(e.ns.overlay.state.ticker)
	toggle(f.controls.enabled, true)
	assert_true(e.ns.db.enabled)
	toggle(f.controls.debug, true)
	assert_true(e.ns.db.debug)
	assert_true(e.ns.debugEnabled)
end)

T.register("options: appearance apply validates all fields atomically and preserves native style", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	f.controls.alpha:SetText("0.3")
	f.controls.red:SetText("bad")
	click(f.controls.apply)
	assert_eq(e.ns.db.alpha, 0.6)
	f.controls.red:SetText("0.2")
	click(f.controls.apply)
	assert_eq(e.ns.db.alpha, 0.3)
	assert_true(e.ns.db.shareNativeStyle)
	toggle(f.controls.native, false)
	f.controls.red:SetText("0.2")
	f.controls.green:SetText("0.4")
	f.controls.blue:SetText("0.8")
	click(f.controls.apply)
	assert_false(e.ns.db.shareNativeStyle)
	assert_eq(e.ns.db.overlayColor[1], 0.2)
	assert_eq(e.ns.db.overlayColor[3], 0.8)
	f.controls.alpha:SetText("-1")
	click(f.controls.apply)
	assert_eq(e.ns.db.alpha, 0.3)
	toggle(f.controls.native, true)
	assert_true(e.ns.db.shareNativeStyle)
	f.controls.alpha:SetFocus()
	click(f.controls.close)
	assert_false(f.controls.alpha:HasFocus())
end)

T.register("options: preview is explicit session only diagnostics opens copy window", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	assert_nil(e.ns.session.fake)
	click(f.controls.preview)
	assert_eq(e.ns.session.fake.value, 1000)
	assert_nil(e.ns.db.showFake)
	click(f.controls.stop)
	assert_nil(e.ns.session.fake)
	click(f.controls.diagnostics)
	assert_true(e.ns.debugWindow:IsShown())
end)

T.register("options: minimap visibility position clicks and drag have no idle updater", function()
	local e = Mocks.NewEnv()
	-- Simulate a minimap becoming available at login; init is also called at startup.
	Minimap = CreateFrame("Frame", nil, UIParent)
	Minimap:SetSize(140, 140)
	GetCursorPosition = function() return 200, 100 end
	e.ns.InitOptions()
	local b = e.ns.minimapButton
	assert_true(b:IsShown())
	assert_nil(b:GetScript("OnUpdate"))
	click(b, "LeftButton")
	assert_true(e.ns.optionsWindow:IsShown())
	click(b, "RightButton")
	assert_true(e.ns.debugWindow:IsShown())
	b:GetScript("OnDragStart")(b)
	assert_true(type(b:GetScript("OnUpdate")) == "function")
	b:GetScript("OnUpdate")()
	assert_near(e.ns.db.minimapAngle, 0, 1e-8)
	b:GetScript("OnDragStop")(b)
	assert_nil(b:GetScript("OnUpdate"))
	e.ns.HandleCommand("minimap off")
	assert_false(b:IsShown())
	assert_true(e.ns.db.minimapHidden)
	e.ns.HandleCommand("enable off")
	e.ns.HandleCommand("minimap on")
	assert_true(b:IsShown(), "settings access must survive disabling prediction")
	assert_eq(e.ns.InitOptions(), nil)
	assert_eq(e.ns.minimapButton, b)
	Minimap, GetCursorPosition = nil, nil
end)

T.register("options: modern Blizzard AddOns category registers once without building settings window", function()
	local e = Mocks.NewEnv()
	local registrations = 0
	Settings = {
		RegisterCanvasLayoutCategory = function(panel, name)
			assert_eq(name, "EllesmereUI HoT Prediction")
			return { panel = panel }
		end,
		RegisterAddOnCategory = function() registrations = registrations + 1 end,
	}
	e.ns.InitOptions()
	e.ns.InitOptions()
	assert_eq(registrations, 1)
	assert_nil(e.ns.optionsWindow)
	assert_true(e.ns.optionsCategoryPanel ~= nil)
	Settings = nil
end)

T.register("options: missing frame API reports gracefully and preview persists only until disabled", function()
	local e = Mocks.NewEnv()
	local create = CreateFrame
	CreateFrame = nil
	assert_nil(e.ns.OpenOptions())
	CreateFrame = create
	local f = e.ns.OpenOptions()
	click(f.controls.preview)
	click(f.controls.close)
	assert_eq(e.ns.session.fake.value, 1000, "closing a menu must not silently change predictions")
	e.ns.OpenOptions()
	toggle(f.controls.enabled, false)
	assert_nil(e.ns.session.fake)
end)
