local function click(widget) widget:GetScript("OnClick")(widget) end
local function contains(text, fragment) return text:find(fragment, 1, true) ~= nil end

T.register("spell catalog: GUI tabs switch cleanly and catalog scrolls without side effects", function()
	local e = Mocks.NewEnv()
	assert_nil(e.ns.optionsWindow)
	local f = e.ns.OpenOptions()
	assert_eq(f.selectedTab, "settings")
	assert_true(f.settingsPage:IsShown()); assert_false(f.spellsPage:IsShown())
	local saved = e.ns.db.queuedSwingEnabled
	f.controls.alpha:SetFocus()
	click(f.controls.spellsTab)
	assert_eq(f.selectedTab, "spells")
	assert_false(f.settingsPage:IsShown()); assert_true(f.spellsPage:IsShown())
	assert_false(f.controls.alpha:HasFocus())
	assert_eq(e.ns.db.queuedSwingEnabled, saved)
	assert_nil(e.ns.session.fake)
	assert_nil(f.spellsPage:GetScript("OnUpdate"))
	local text = f.catalogText:GetText()
	assert_true(contains(text, "Rejuvenation")); assert_true(contains(text, "25299"))
	assert_true(contains(text, "Riptide")); assert_true(contains(text, "1239243"))
	assert_true(contains(text, "Heroic Strike")); assert_true(contains(text, "47450"))
	assert_true(contains(text, "Other players' HoTs are NOT implemented"))
	assert_true(contains(text, "CANDIDATES: MANUAL / OBSERVATION ONLY"))
	assert_true(contains(text, "Lifebloom")); assert_true(contains(text, "Germination"))
	assert_true(f.catalogScroll:GetVerticalScrollRange() > 0)
	f.catalogScroll:GetScript("OnMouseWheel")(f.catalogScroll, -10)
	assert_true(f.catalogScroll:GetVerticalScroll() > 0)
	click(f.controls.settingsTab)
	assert_true(f.settingsPage:IsShown()); assert_false(f.spellsPage:IsShown())
	click(f.controls.spellsTab)
	click(f.controls.close)
	assert_false(f:IsShown())
	e.ns.OpenOptions()
	assert_eq(e.ns.optionsWindow, f); assert_eq(f.selectedTab, "spells")
end)

T.register("spell catalog: every registry ID appears and custom/disabled entries refresh on open", function()
	local e = Mocks.NewEnv()
	e.ns.HandleCommand("spell add 99999 CustomHoT")
	e.ns.HandleCommand("spell remove 774")
	local text = e.ns.BuildSpellCatalog()
	assert_true(contains(text, "CustomHoT")); assert_true(contains(text, "99999"))
	assert_true(contains(text, "Disabled by your settings: 774"))
	for id in pairs(e.ns.spells.BASE) do assert_true(contains(text, tostring(id))) end
	for id in pairs(e.ns.queuedSwing.spells) do assert_true(contains(text, tostring(id))) end
	local f = e.ns.OpenOptions()
	click(f.controls.spellsTab)
	e.ns.HandleCommand("spell add 99998 NewHoT")
	assert_false(contains(f.catalogText:GetText(), "NewHoT"), "snapshot has no background updater")
	click(f.controls.settingsTab); click(f.controls.spellsTab)
	assert_true(contains(f.catalogText:GetText(), "NewHoT"))
	assert_eq(f.catalogScroll:GetVerticalScroll(), 0)
	assert_nil(e.ns.session.fake)
end)

T.register("spell catalog: text renders above the decorative catalog background", function()
	local e = Mocks.NewEnv()
	local f = e.ns.OpenOptions()
	click(f.controls.spellsTab)
	assert_true(f.spellsPage:IsShown())
	-- The catalog backdrop is a BACKGROUND draw-layer texture on the catalog
	-- frame; a child frame here would also cover the window tabs' hit area.
	assert_not_nil(Mocks.FindTexture(f.spellsPage, "BACKGROUND"), "catalog background must be a texture")
	assert_eq(#Mocks.OpaqueChildFrames(f.spellsPage), 0, "no opaque child panel may cover the catalog")
	assert_true(Mocks.IsRegionVisible(f.catalogText), "catalog text must stay readable")
	-- Background decoration is a texture: it has no mouse surface at all.
	local fill = Mocks.FindTexture(f.spellsPage, "BACKGROUND")
	assert_nil(fill.EnableMouse, "background decoration must not intercept mouse input")
	assert_true(f.controls.spellsTab:IsShown() and f.controls.settingsTab:IsShown())
end)
